### PR TITLE
Multitarget netstandard2.0 and net45

### PR DESCRIPTION
**Pull request by asherber**
A multitargeted NuGet package will allow a greater range of uses. In particular, some of the ADO.NET data providers are a little more stable in framework rather than .NET Standard; distributing only a Standard version of this package forces the .NET Standard version of AsyncPoco, which in turn forces .NET Standard data providers.

Note that I also deleted the .nuspec files and put the build information directly into the .fsproj/.csproj file, which makes it easier to get the right assemblies in the right directories. Now you can just do `dotnet pack` from the solution directory (or each project directory) to generate the packages. (`dotnet pack -c Release` to specifically pack release versions.)

### CODE REVIEW

**Comment by d-p-y** [comment]
Thank you!

**Comment by asherber** [comment]
Happy to help -- thanks for accepting the PRs!

**Comment by d-p-y** [comment]
I've bumped version number and also published it in nuget (includes both PRs)

**Comment by asherber** [comment]
Excellent, thanks!

**Pull request merged**
